### ISSUE TITLE
Front end updates - 09 March 2022

### ISSUE THREAD

**Issue by KashunEnspirer** [Enspirer/EnspirerWT#1]
Please refer the doc for updates

https://docs.google.com/document/d/1WbxiPEyKGSdfZdttZEY6zDbnhU_r8UvDESEW3XB-PD4/edit

**Comment by achinthatallentor** [comment]
Frontend updates - 08 Mar 2022 - Done !

**Comment by achinthatallentor** [comment]
Frontend Updates - 09 Mar 2022

- Section 3
- Section 3 - Card 1
- Section 3 - Card 2
- Section 3 - Card 3

Done !

**Comment by achinthatallentor** [comment]
Frontend Updates - 09 Mar 2022

- Section 4 

Done !

**Comment by achinthatallentor** [comment]
- Home Page 
- Contact Us Page

Done !

**Comment by achinthatallentor** [comment]
- Products Page

Done !
